// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

// PublishOrderPlaced provides a mock function with given fields: ctx, orderID, userID, bookIDs
func (_m *KafkaProducer) PublishOrderPlaced(ctx context.Context, orderID int, userID string, bookIDs []int) error {
	ret := _m.Called(ctx, orderID, userID, bookIDs)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderPlaced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, []int) error); ok {
		r0 = rf(ctx, orderID, userID, bookIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKafkaProducer creates a new instance of KafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaProducer {
	mock := &KafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
