// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yourorg/bookshop/internal/domain"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetOrCreate provides a mock function with given fields: ctx, id, email, isAdmin
func (_m *UserService) GetOrCreate(ctx context.Context, id string, email string, isAdmin bool) (*domain.User, error) {
	ret := _m.Called(ctx, id, email, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*domain.User, error)); ok {
		return rf(ctx, id, email, isAdmin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *domain.User); ok {
		r0 = rf(ctx, id, email, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, id, email, isAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
