version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: bookshop
      POSTGRES_PASSWORD: bookshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/bookshop
      KC_DB_USERNAME: bookshop
      KC_DB_PASSWORD: bookshop
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/init-users.sh:/opt/keycloak/init-users.sh
      - ./keycloak/init-users.env:/opt/keycloak/init-users.env

  bookshop:
    build: .
    depends_on:
      - postgres
      - redis
      - kafka
      - keycloak
    environment:
      CONFIG_PATH: /app/configs/config.yaml
    ports:
      - "8081:8081"
    volumes:
      - ./configs:/app/configs
      - ./migrations:/app/migrations

volumes:
  pgdata: 